import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.evaluate(() => { localStorage.clear(); });
await page.reload({ waitUntil: 'networkidle' });
await page.locator('nav button').nth(3).click();
await page.waitForTimeout(1200);
await page.locator('summary', { hasText: "Calculateur d'artillerie" }).click();
await page.waitForTimeout(400);
await page.locator('button', { hasText: 'Placer le canon' }).click();
await page.mouse.click(520, 450);
await page.waitForTimeout(300);
await page.locator('button', { hasText: 'Placer la cible' }).click();
await page.mouse.click(680, 400);
await page.waitForTimeout(500);
await page.screenshot({ path: process.env.S + '/arty-map.png' });
const sol1 = await page.locator('.font-mono.text-lg').first().textContent().catch(()=>null);
console.log('after place:', sol1);
// drag the target marker
await page.mouse.move(680, 400);
await page.mouse.down();
await page.mouse.move(760, 560, { steps: 14 });
await page.mouse.up();
await page.waitForTimeout(400);
await page.screenshot({ path: process.env.S + '/arty-drag.png' });
const sol2 = await page.locator('.font-mono.text-lg').first().textContent().catch(()=>null);
console.log('after drag:', sol2);
await browser.close();
